[Service]
ExecStartPre=/bin/sleep 3

[Service]
Environment="XDG_SESSION_TYPE=wayland"
Environment="XDG_RUNTIME_DIR=/run/user/1000"
Environment="WAYLAND_DISPLAY=wayland-1"
Environment="DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus"
